#!/usr/bin/env bun
/**
 * Build-time script — run ONLY on your dev/CI machine.
 * Reads skills-source/<skill>/SKILL.md, encrypts each with AES-256-CBC,
 * and writes src/skills/encrypted.ts (compiled into the binary).
 *
 * Required env var:
 *   ISTACK_BUILD_KEY — 32-byte hex string (64 chars)
 *     - First 16 bytes → embedded in binary as __ISTACK_BK__
 *     - Last  16 bytes → served per-user by the license server as key_half
 *
 * Generate a key: openssl rand -hex 32
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { createCipheriv, randomBytes } from 'crypto';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const SKILLS_DIR = join(ROOT, 'skills-source');
const OUT_FILE = join(ROOT, 'src/skills/encrypted.ts');

const buildKey = process.env.ISTACK_BUILD_KEY;
if (!buildKey || buildKey.length !== 64) {
  console.error('');
  console.error('  ERROR: ISTACK_BUILD_KEY must be a 64-char hex string (32 bytes)');
  console.error('  Generate one: openssl rand -hex 32');
  console.error('');
  process.exit(1);
}

if (!existsSync(SKILLS_DIR)) {
  console.error(`  ERROR: skills-source/ not found at ${SKILLS_DIR}`);
  process.exit(1);
}

const KEY = Buffer.from(buildKey, 'hex'); // 32 bytes
const BINARY_HALF = KEY.subarray(0, 16).toString('hex');  // goes into __ISTACK_BK__ build env
const LICENSE_HALF = KEY.subarray(16).toString('hex');    // served by license server

const encrypted: Record<string, string> = {};
let count = 0;

for (const entry of readdirSync(SKILLS_DIR, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const skillFile = join(SKILLS_DIR, entry.name, 'SKILL.md');
  if (!existsSync(skillFile)) continue;
  const name = entry.name;
  const content = readFileSync(skillFile, 'utf8');

  const iv = randomBytes(16);
  const cipher = createCipheriv('aes-256-cbc', KEY, iv);
  const enc = Buffer.concat([cipher.update(content, 'utf8'), cipher.final()]);
  // Blob = IV (16 bytes) + ciphertext, base64-encoded
  encrypted[name] = Buffer.concat([iv, enc]).toString('base64');
  count++;
  console.log(`  ✓ Encrypted /${name}`);
}

const ts = `// AUTO-GENERATED by scripts/encrypt-skills.ts — DO NOT EDIT — DO NOT COMMIT
// Regenerate: ISTACK_BUILD_KEY=<key> bun run encrypt-skills
export const ENCRYPTED_SKILLS: Record<string, string> = ${JSON.stringify(encrypted, null, 2)};
`;

writeFileSync(OUT_FILE, ts, 'utf8');

console.log('');
console.log(`  ${count} skill(s) encrypted → src/skills/encrypted.ts`);
console.log('');
console.log('  ── CI/Build secrets to set ────────────────────────────────');
console.log(`  ISTACK_BK (in binary via __ISTACK_BK__): ${BINARY_HALF}`);
console.log(`  LICENSE_KEY_HALF (served by license API): ${LICENSE_HALF}`);
console.log('  ────────────────────────────────────────────────────────────');
console.log('');
console.log('  IMPORTANT: Store LICENSE_KEY_HALF in your license server DB.');
console.log('  IMPORTANT: Set ISTACK_BK as a CI secret → passed to bun build');
console.log('             via --define "__ISTACK_BK__=\\\"<value>\\\""');
console.log('');
